# Generated by Django 2.2.3 on 2019-07-13 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('SN', 'Não Informado')], max_length=2)),
                ('email', models.EmailField(max_length=254)),
                ('celular', models.CharField(max_length=11)),
                ('nascimento', models.DateField()),
                ('pais_origem', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=8)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cadastro',
            },
        ),
    ]
