# Generated by Django 2.2.3 on 2019-07-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='cadastro',
            name='pais_origem',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='medalhas',
            field=models.CharField(choices=[('oc', 'Octopus'), ('vt', 'Ventosa'), ('tc', 'Tentáculo'), ('tn', 'Tinta'), ('pv', 'Perseverante'), ('pc', 'Parceiro'), ('an', 'Aniversário'), ('ft', 'Festivo')], default='oc', max_length=2),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='pontos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(default='4002-8922', max_length=12),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='senha',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='usuario',
            field=models.CharField(max_length=100),
        ),
    ]
