# Generated by Django 2.2.3 on 2019-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190714_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(default='', max_length=12),
        ),
    ]
